### ISSUE TITLE
Error raises when re-ranking.

### ISSUE THREAD

**Issue by sonsongithub** [gtolias/rmac#1]
I'd like to reproduce your research using your codes.
But, some errors prevent it.

I use 'matconvnet-1.0-beta25' and 'imagenet-caffe-alex.mat' that are downloaded from vlfeat.org, macOS 10.12.6, MATLAB2017a.

```
Error using bsxfun
Non-singleton dimensions of the two input arrays must match each other.

Error in apply_whiten (line 8)
x_ = bsxfun (@minus, x, xm);  % Subtract the mean

Error in test>@(y)vecpostproc(sum(vecpostproc(apply_whiten(y,mean_vectors_train,eigvec,eigval)),2))

Error in test (line 166)
            vecs_bestbox = cellfun(@(y) vecpostproc(sum(vecpostproc(apply_whiten(y, mean_vectors_train, eigvec, eigval)), 2)), vecs_bestbox, 'un', 0);
```

And, I got following error when I used 'matconvnet-1.0-beta15', macOS 10.12.6, MATLAB2017a.

```
Error using vl_simplenn (line 252)
Unknown layer type lrn

Error in rmac_regionvec (line 12)
	rnet = vl_simplenn(net, I);

Error in test>@(x)rmac_regionvec(imread(x),net,L)

Error in test (line 90)
            [vectors, conv3d] = cellfun(@(x) rmac_regionvec(imread(x), net, L), im_fn_test, 'un', 0);
```

What should I do for this issue?

**Comment by gtolias** [comment]
The appropriate network is automatically downloaded in the test script. It is different from the one currently provided on vlfeat.org, in fact it is an older version from vlfeat.org. Given that the downloaded network is used, and that matconvnet-1.0-beta15 is used, which is again automatically downloaded, the test.m script should run smoothly. In practice, I was not able to reproduce this error. I test on Linux and Matlab R2016b.

**Comment by sonsongithub** [comment]
Thank you for replying.
I will try to do it, once.

**Comment by sonsongithub** [comment]
I tried it according to your advice. I had a some progress.
But, I got the following error....
Test code failed to execute "reranking" using R-MAC.
If you have some ideas to resolve this issue, let me know...

Thank you.

```
Extracting features
Learning PCA-whitening
Applying PCA-whitening
Process query images
Retrieval
mAP, without re-ranking = 0.7295
Error using bsxfun
Non-singleton dimensions of the two input arrays must match each other.

Error in apply_whiten (line 8)
x_ = bsxfun (@minus, x, xm);  % Subtract the mean

Error in test>@(y)vecpostproc(sum(vecpostproc(apply_whiten(y,Xm,eigvec,eigval)),2))

Error in test (line 152)
		    vecs_bestbox = cellfun(@(y) vecpostproc(sum(vecpostproc(apply_whiten(y, Xm, eigvec, eigval)), 2)), vecs_bestbox, 'un', 0);
```

**Comment by albanie** [comment]
Hi @sonsongithub, had a similar problem - the issue in my case it was due to the usage of an int array pointer [here](https://github.com/gtolias/rmac/blob/master/aml.c#L37).  This causes the `aml` function to run over empty regions. Was able to fix by changing [this line](https://github.com/gtolias/rmac/blob/master/test.m#L9) to `mex -compatibleArrayDims aml.c`.

**Comment by sonsongithub** [comment]
@albanie 
Thank you.
I'll try it.

**Comment by gtolias** [comment]
Thank you @sonsongithub for pointing this out and @albanie for the solution. Apparently -compatibleArrayDims was the default case in earlier matlab versions. I have now tested the code with Matlab 9.2 and updated it to work with matconvnet-1.0-beta25.
